### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nesjett** [nesjett/unreal-engine-crawling-system#11]
- [x]  Configurable **Camera limits**
![image](https://github.com/nesjett/unreal-engine-crawling-system/assets/7051231/a0f8bc20-2474-469d-b844-62bf1be7bca1)

- [ ]  Customizable behavior to enter the route, with examples provided.
- [x]  **Debugging tools**: Add some more info to the widget, like character speeds and current rotations, facing dirs?
- [ ]  Examples and caveats provided.
- [x]  Fix issue that makes you start crawling when you should not...
- [x] Fix 3rd person character rotation
- [ ] CrawlingMovement component private methods have been converted to protected to facilitate customization by inheritance.

**Comment by nesjett** [comment]
Add to the docs how to disable collision for custom pawns:
![image](https://github.com/nesjett/unreal-engine-crawling-system/assets/7051231/18220520-a41f-44a5-b18c-7014340c4925)

**Comment by nesjett** [comment]
Add info to the wiki on how to add debug child actors that will get cleared when toggling debug (using CS_Debug tag)
![image](https://github.com/nesjett/unreal-engine-crawling-system/assets/7051231/5206625b-7ac5-4113-85e8-f08d596d6525)

**Comment by nesjett** [comment]
Show how to enable debug widget in a per-actor basis (only way possible right now)
![image](https://github.com/nesjett/unreal-engine-crawling-system/assets/7051231/c975abac-90b0-4de1-b65d-bc6a3e0cba02)

**Comment by nesjett** [comment]
Tutorial to create a route that requires pressing a key to enter

**Comment by nesjett** [comment]
Add info about functional automated tests:
![image](https://github.com/nesjett/unreal-engine-crawling-system/assets/7051231/f8f60592-7904-406b-bca2-f3fefd8908c5)

**Comment by isedwards** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
gkze, @SDPOPT, @ddxxgg688, @sivarajp, @xu-zekun, @overstartup, @ariel-frischer, @jackiezhang2017, @sinojelly, @ambrosektal, @epzee, @fubastshitardck, @svahidnajafi, @edwardyi, @iwangli0909, @volksvagen, @sumnone, @mgraillat, @4R4T4, @ErnestAgel, @Avangarde2225, @VRanger, @williamdooo, @wuwenjie1992, @Sachin-0716, @triplewood, @sihai90, @ande128, @sabodaha, @frogsuite, @Notahandle, @willchenjian, @sylviadream, @jrhui, @zy17607118702, @RenAndrew, @RMeeno, @revzacool, @powerdoom, @omars7z, @gilbertqin, @huanbd, @chiyoung01, @Gustavoperinazzo, @super-quants, @hunter0101010101010, @hugo9773, @Buckstraders, @caino, @bcrpntr

**Comment by isedwards** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
taoguan, @sbhamad, @atimangel, @liulaojian, @s616050079, @Mr-Skully, @RippleWind, @asloan7, @Revanthre001, @nipunpatel86, @JFWooten4, @softdream1981, @JwaveDev, @anri-asaturov, @lechariot, @Natep23, @amirphl, @Rian23-R4, @afterlife88, @geschem, @sahebsunny, @wang-shun, @kenanilgun, @dendisuhubdy, @nick418, @jcjc81, @Jiqian233, @perez8179, @lalitkale, @bvan512, @maxrena, @yuanweixin, @mo2menelzeiny, @oushaonan, @RudzaniNdaa, @kuznetskriss, @solotourist, @NzzyDev, @JianWang6, @hn2, @kacha94, @qwhh514, @theKosh, @jonnermut, @a3ix1klarai, @HydraJedi, @Kongys17, @rcholic, @dez113-c, @hijoe320

**Comment by nesjett** [comment]
Trubleshooting what happens if your character mesh stays rotated after exiting the route.

**Comment by nesjett** [comment]
Wont do more at this point
